[profile.default]
src = "src"
out = "out"
libs = ["lib"]
eth_rpc_url = "https://rpc.testnet.arc.network"
chain_id = 5042002
# Etherscan-like explorer verification config if needed later
# verifier = "blockscout" 
# verifier_url = "https://testnet.arcscan.app/api"
